/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.matrixstuff.matrixlib;

import org.junit.Test;
import static org.junit.Assert.*;

public class MatrixTest {
    @Test
    public void testMatrix_getValues() {
        Matrix matrix = Matrix.of(new Double[]{1.2,0d,5.2,900d});
        assertArrayEquals(new Double[]{1.2,0d,5.2,900d}, matrix.getValues());
    }
}
