/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mathstuff.mathlib;

import com.matrixstuff.matrixlib.Matrix;
import org.junit.Test;
import static org.junit.Assert.*;

public class MathLibraryTest {
    @Test
    public void convert_returnsValues() {
        MathLibrary mathLibrary = MathLibrary.create();
        Double[] values = mathLibrary.convert6("1.3,5.6,9,100");
        assertArrayEquals(new Double[] {1.3, 5.6, 9d, 100d}, values);
    }

    public void convert_returnsMatrix() {
        MathLibrary mathLibrary = MathLibrary.create();
        Matrix matrix = mathLibrary.convertToMatrix("1.3,5.6,9,100");
        assertArrayEquals(new Double[] {1.3, 5.6, 9d, 100d}, matrix.getValues());
    }
}
