/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.matrixstuff.matrixlib;

public class Matrix {
    private Double[] _values;
    private Matrix(Double[] values) {
        _values = values;
    }

    public static Matrix of(Double[] values) {
        return new Matrix(values);
    }

    public Double[] getValues() {
        return _values;
    }
}
